### ISSUE TITLE
suggestion: use withr::local_seed() in tests

### ISSUE THREAD

**Issue by maelle** [EllaKaye/aperol#3]
instead of `set.seed()` that changes the global state. https://withr.r-lib.org/reference/with_seed.html

:cocktail:

**Comment by EllaKaye** [comment]
Thanks for the tip @maelle 😄

**Comment by maelle** [comment]
I never miss an opportunity to plug {withr} :joy:

**Comment by EllaKaye** [comment]
A good reason to follow package good-practice, even for silly packages - I get to learn about package better-practice 😄

(I knew about {withr} because of `with_options()`, but didn't know about the seed functionality).
